Editing Email Template
cornell-dti/zing-lsc pull request #117
Opened 2022-10-28 10:53 UTC by jewang25

### Summary 
- added basic functionality for editing email template in the email modal. 
- can click edit button to change the html for the template and then save the new template

This pull request is the first step towards implementing feature to edit emails on email modal

- implemented the basic structure of this feature by adding a textfield and saving the new template
- work in progress: still need to receive designs for this feature and implement the new design 

### Test Plan 

- testing in progress: tested by printing out the template once the email sent button is clicked and seeing if the changes were saved
- testing both match and no match templates
- testing if the new template is preserved when back button is clicked

2022-11-18 00:47 UTC, rgu0114 reviewed
This looks rly good Jessica, nice work! I like how you used an inlined function to replace the html pretty cleanly, and I don't see any issues with this PR. Could you also attach screenshots/recordings of what this looks like?

2022-12-02 22:12 UTC, mluo24 requested changes
Hi Jessica, thanks for taking on this task. I've mentioned before that there are now designs that you can reference here: [https://www.figma.com/file/Dc6q3OOEV4JnHLs5T7VRXZ/Prachi's-Working-File?node-id=1%3A38561&t=unUrNvsIxW1cVBB5-0](https://www.figma.com/file/Dc6q3OOEV4JnHLs5T7VRXZ/Prachi%27s-Working-File?node-id=1%3A38561&t=unUrNvsIxW1cVBB5-0)

There are also some visual bugs, like this one: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/69130822/205398500-a60e8c48-4910-4026-af67-18565dcb4753.png">

Other than that, the functionality seems alright, besides a small nit I made about how the saving does not really show feedback that you have actually saved something. Good work on that!

2022-12-02 22:12 UTC, mluo24 commented on frontend/src/modules/EditZing/Components/EmailModal.tsx
> +      )
Change this part to the designs

2022-12-02 22:12 UTC, mluo24 commented on frontend/src/modules/EditZing/Components/EmailEdit.tsx
> +  )
I'm not sure if it's the fault of this component or somewhere else, either way the styling is a little messed up.

2022-12-02 22:12 UTC, mluo24 commented on frontend/src/modules/EditZing/Components/EmailEdit.tsx
> +    console.log('clicked')
You can delete the console.logs

2022-12-02 22:12 UTC, mluo24 commented on frontend/src/modules/EditZing/Components/EmailEdit.tsx
> +  }
This doesn't give any feedback when you click. I didn't realize anything got changed until I pressed back and the changes were there.

2022-12-09 05:30 UTC, mluo24 approved these changes
Thanks for fixing the styling. I tested this out, and everything looks good! I think one noteworthy part is that the subject can't be edited, but since this feature is functional and it's possible that that's not necessary, I think we can overlook that until they say they need it. 

Just fix lint errors and you can merge :)

2022-12-17 19:26 UTC, merged