Flag a course
cornell-dti/zing-lsc pull request #160
Opened 2023-03-23 21:18 UTC by b3njamint

### Current Status 

Can flag and unflag course at free will. Changing pages and jumping around in history will not cause problems.

### Summary 

This pull request allows LSC to flag a course when there is a "bad situation," or when there are potential matches for a course but they are not ideal (i.e. there is only one grad student and one freshmen waiting to be matched. Such a flag would remind LSC to not click the match button.

- [x] implemented X
- [ ] fixed Y

### Test Plan 

The dashboard. You can see the little bookmark icons (could be changed later).
<img width="1512" alt="Screen Shot 2023-04-16 at 9 15 59 PM" src="https://user-images.githubusercontent.com/52147838/232356410-4d969317-8fb5-48b9-ad45-163f22f3d92b.png">
The emulator. As you can see, there is no flag field right now. Note that this is important, because even if there is no flag field, there are no null problems.
<img width="1512" alt="Screen Shot 2023-04-16 at 9 16 32 PM" src="https://user-images.githubusercontent.com/52147838/232356489-8cc5ccc5-3ac2-4931-83d4-252b74741207.png">
Oh no, a bad situation!
<img width="1512" alt="Screen Shot 2023-04-16 at 9 17 05 PM" src="https://user-images.githubusercontent.com/52147838/232356634-3fe8436c-7586-4409-a93b-8f1e2a54ee76.png">
Let's flag it.
<img width="1512" alt="Screen Shot 2023-04-16 at 9 17 14 PM" src="https://user-images.githubusercontent.com/52147838/232356671-90492a85-4006-4192-8e48-9bc23b2d9b04.png">
A new field is created in the Firebase, and set accordingly. We can refresh, move back and forth in history and the bookmark will still be in its correct state.
<img width="1512" alt="Screen Shot 2023-04-16 at 9 20 18 PM" src="https://user-images.githubusercontent.com/52147838/232356687-041e2eab-96ad-4750-b804-2cceafec39b3.png">

### Notes 

Next steps (look out for a future PR):
- [ ] remove flag when new student joins
- [ ] maybe add some filter option to filter for flags?

### Breaking Changes 

- Changed the CourseContext (added a field to Firebase). I don't see any problems through testing but please let me know.

2023-04-17 01:03 UTC, rgu0114 reviewed
Nice work Benji! I like how you separated out all your functions to flag a course and used defensive programming to set the flagged field of CourseCard. Everything looks good for the most part, but it would be great if you could describe your testing plan a bit more.

2023-04-17 01:10 UTC, b3njamint commented
> Nice work Benji! I like how you separated out all your functions to flag a course and used defensive programming to set the flagged field of CourseCard. Everything looks good for the most part, but it would be great if you could describe your testing plan a bit more.

Thanks for the feedback. I haven't updated the PR description yet, but will do that right now.

2023-04-25 18:59 UTC, mluo24 approved these changes
Good job Benji! I like your integration with the CourseContext and the elegant solution to this! I played around with it a bit and it works well.

I'm looking forward to your second PR :)

2023-04-25 19:06 UTC, mluo24 requested changes
wait I forgot to say that something went wrong when I ran it because it was a syntax error. I pointed it out in the code.

2023-04-25 19:06 UTC, mluo24 commented on backend/functions/src/course/routes.ts
> +      res.status(500).send({ message: err.message })
You're missing braces and parentheses at the end.

2023-04-26 01:45 UTC, mluo24 approved these changes
works now! good job!

2023-04-26 02:26 UTC, merged