Scuffed Survey Template Rework
cornell-dti/zing-lsc pull request #41
Opened 2022-04-17 18:29 UTC by CollinWoo

### Summary 

This pull request implements the reworked survey questions and step template design shown [here](https://www.figma.com/file/9zueLCvKT7BBMYi8Dt8Ukp/Zing-LSC?node-id=2394%3A234446). See the second screen onwards from http://localhost:3000/survey.

- [x] updated survey questions in Questions.json by rewording response options and deleting COVID-specific questions
- [x] updated buttons and progress bar to match the Figma design
- [x] made it so scrollbars are added if survey options overflow the card (this wasn't specified in the design but I thought it made sense) 
- [x] attempted to keep the design responsive, although I'm unsure about how well I accomplished this 

### Test Plan 

Changes were mostly visual so testing was done by comparing the Figma to the actual frontend. Screenshots of the frontend implementation are below:

<img width="550" alt="Screen Shot 2022-04-17 at 1 53 06 PM" src="https://user-images.githubusercontent.com/45516888/163726874-930530b0-76d6-4ed0-921a-e347e69d1af8.png">
<img width="550" alt="Screen Shot 2022-04-17 at 1 54 00 PM" src="https://user-images.githubusercontent.com/45516888/163726880-b6a4a640-4e30-45d7-8fb5-667581a55967.png">

### Notes 
- most of the design changes were accomplished with inline styling in StepTemplate.tsx. This is probably not good practice but I was too afraid to touch the existing styling for components.
- Some of the non-template related styling (text boxes, radio buttons) does not match the Figma. I only edited the survey template so these were not updated.

2022-04-20 06:49 UTC, Coreball requested changes
Good work updating the survey questions and figuring out how to use MUI components such as IconButton! Thanks for the screenshots and detailed notes in the PR, I have a few comments on them in addition to the comments I made in the code.

For the design changes, try to be un-afraid to touch the existing styling/components! The faster you do this, the quicker you'll learn how to use them + get familiar coding in the project.

We should also avoid having PRs that would break main in a significant way when merged (or have the PR that would fix things ready to go). This PR should include the changes to handle the reduced question set on the backend, provided they are not too major. When people branch off of main later, it would be best if they are able to work on new code and test it without running into problems submitting the survey. This is especially important for this PR because student survey submissions form the basis for most other testing.

2022-04-20 06:49 UTC, Coreball commented on frontend/src/modules/Core/Questions/Questions.json
> +      "ILR": "ILR"
HumEc should not have been deleted. If you notice something unusual about the designs make sure to ask! I talked to Alyssa and it should have been there. A&S > CAS officially, let's prefer that here too.

2022-04-20 06:49 UTC, Coreball commented on frontend/src/modules/Survey/Components/StepTemplate.tsx
> +          <div style={{ marginLeft: 'auto', textAlign: 'center' }}>
I'm not sure how I feel about raw divs being used and styled this way. It definitely works, but I am hesitant towards adding a third styling solution on top of the two we're already using, Styled and MUI `sx`. Ideally, we would have one styling solution used everywhere to make things simpler (or a few, if the situations in which each is preferred are clearly delineated).

2022-04-20 19:06 UTC, CollinWoo commented on frontend/src/modules/Core/Questions/Questions.json
> +      "ILR": "ILR"
kk fixed the questions to include humec and changed CAS to A&S

2022-04-20 19:39 UTC, Coreball commented
Also forgot to add this but the scroll looks kind of weird on my computer (macOS, Firefox)

![Screen Shot 2022-04-19 at 22 23 27](https://user-images.githubusercontent.com/22627336/164309604-0ca7824a-49b1-4256-af7e-4dd251ee78b8.png)

2022-04-28 02:14 UTC, Coreball approved these changes
Good work, let's just get this merged in to keep this PR small and focused. We can clean up other parts of the survey later. Since there are conflicts, you'll have to merge main into your branch to fix them.

2022-04-28 02:14 UTC, Coreball commented on backend/functions/src/matching/functions.ts
> +    ()
You can remove the sort entirely

2022-05-01 18:03 UTC, jessica0801 reviewed
great job on this PR!! updating all the fields and information was incredibly important, and I am excited to see this product be updated and ready for use. I also loved the   incorporation of MUI into a lot of these elements.

2022-05-01 18:03 UTC, jessica0801 commented on frontend/src/modules/Survey/Components/StepBegin.tsx
> +import { IconButton, Box } from '@mui/material'
Nice use of the mui icons! it makes the code much simpler and the  look more consistent

2022-05-08 13:20 UTC, merged